version: '3'
services:
  node-app:
    build:
      context: ./my-node-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./my-node-app:/usr/src/app
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/mydatabase"
  mongodb:
    image: mongo:4
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb-data:
